### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KolesnichenkoDS** [wi-browser/wi#1]
- [ ] Command-line arguments
- [ ] [Sam's](http://sam.cat-v.org/) [structural regular expression](http://doc.cat-v.org/bell_labs/structural_regexps/) based [command language](http://doc.cat-v.org/bell_labs/sam_lang_tutorial/) support
- [ ] Downloads
- [ ] [Greasemonkey](http://www.greasespot.net/)-like userscripts support
- [ ] JavaScript API for browser configuration
